usaxs.devices.blackfly_module.MyPointGreyDetector:
- name: blackfly_det
  prefix: "usxFLY1:"
  labels: ["camera", "area_detector"]

usaxs.devices.blackfly_module.MyPointGreyDetectorTIFF:
- name: blackfly_optical
  prefix: "usxFLY2:"
  labels: ["camera", "area_detector"]

usaxs.devices.pilatus_module.MyPilatusDetector:
- name: saxs_det
  prefix: "usaxs_pilatus3:"
  labels: ["camera", "area_detector"]

usaxs.devices.pilatus_module.MyEigerDetector:
- name: waxs_det
  prefix: "usaxs_eiger1:"
  labels: ["camera", "area_detector"]
